spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: 1234
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
